// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyvdgrullrpsznxnfhvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95dmRncnVsbHJwc3pueG5maHZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MDMzODMsImV4cCI6MjA3MTM3OTM4M30.GQSYZZMLFjHauCRo5AeaS1HCBnD_jCv_MGPfN3oDT1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});